# User config
author: "Ksenia Bataeva"
tagline: "kclo"
whoami: "Frontend Developer"
tesis: Удобный интерфейс, красивая упаковка, работоспособная системаs
description: "Умею делать интерактивные страницы с графиками и картами"
keywords: "kclo"
email: "kclosu@gmail.com"
# linkedin: "https://www.linkedin.com/"
# twitter: "https://twitter.com/"
github: "https://github.com/kclosu"
telegram: "https://t.me/kclosu"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
collections:
  projects:
    output: true
    permalink: /:collection/:name